"""
IBM Granite LLM Tool — calls the watsonx.ai Granite-4 model directly
for open-ended career counselling analysis tasks.
"""
import os
import requests
from typing import Optional
from pydantic import BaseModel, Field
from ibm_watsonx_orchestrate.agent_builder.tools import tool, ToolPermission

_WX_URL = "https://us-south.ml.cloud.ibm.com/ml/v1/text/generation?version=2023-05-29"
_MODEL_ID = "ibm/granite-4-h-small"
_PROJECT_ID = "96976d6c-b08d-4aa0-86e8-8c67fdb04468"


def _get_api_key() -> str:
    return os.environ.get("IBM_API_KEY", "JFgzcUApwzdyD9TWf1UfYhH2dqyfbIcd-ij6uRHVS392")


def _get_iam_token(api_key: str) -> str:
    resp = requests.post(
        "https://iam.cloud.ibm.com/identity/token",
        headers={"Content-Type": "application/x-www-form-urlencoded"},
        data="grant_type=urn:ibm:params:oauth:grant-type:apikey&apikey=" + api_key,
        timeout=30,
    )
    resp.raise_for_status()
    return resp.json()["access_token"]


class GraniteInput(BaseModel):
    """Input for the IBM Granite LLM career analysis tool."""
    prompt: str = Field(..., description="The prompt or question to send to IBM Granite for career counselling analysis.")
    max_new_tokens: Optional[int] = Field(default=512, description="Maximum number of tokens to generate.")
    temperature: Optional[float] = Field(default=0.7, description="Sampling temperature between 0 and 1.")


class GraniteOutput(BaseModel):
    """Output from the IBM Granite LLM career analysis tool."""
    generated_text: str = Field(..., description="The text generated by IBM Granite.")
    model_id: str = Field(..., description="The model ID that produced the response.")
    stop_reason: str = Field(..., description="Why the model stopped generating.")


# Ensure Pydantic v2 models are fully built before the @tool decorator runs
GraniteInput.model_rebuild()
GraniteOutput.model_rebuild()


@tool(permission=ToolPermission.READ_ONLY)
def call_granite_llm(input: GraniteInput) -> GraniteOutput:
    """
    Call the IBM Granite-4 language model hosted on IBM watsonx.ai for
    open-ended career counselling analysis, advice generation, or text
    classification tasks.

    Args:
        input (GraniteInput): Prompt and optional generation parameters.

    Returns:
        GraniteOutput: The generated text along with model metadata.
    """
    api_key = _get_api_key()
    token = _get_iam_token(api_key)
    payload = {
        "model_id": _MODEL_ID,
        "project_id": _PROJECT_ID,
        "input": input.prompt,
        "parameters": {
            "decoding_method": "sample",
            "max_new_tokens": input.max_new_tokens or 512,
            "temperature": input.temperature or 0.7,
            "repetition_penalty": 1.05,
        },
    }
    headers = {
        "Accept": "application/json",
        "Content-Type": "application/json",
        "Authorization": "Bearer " + token,
    }
    response = requests.post(_WX_URL, headers=headers, json=payload, timeout=60)
    response.raise_for_status()
    data = response.json()
    result = data["results"][0]
    return GraniteOutput(
        generated_text=result.get("generated_text", "").strip(),
        model_id=data.get("model_id", _MODEL_ID),
        stop_reason=result.get("stop_reason", "unknown"),
    )
